# Generated by Django 4.2.9 on 2026-01-30 07:01

import apps.engineering.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drawing_number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('drawing_type', models.CharField(choices=[('production', 'Production Drawing'), ('assembly', 'Assembly Drawing'), ('detail', 'Detail Drawing'), ('layout', 'Layout Drawing'), ('schematic', 'Schematic'), ('3d', '3D Model'), ('other', 'Other')], default='production', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('revision', models.CharField(default='A', max_length=10)),
                ('is_latest', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to=apps.engineering.models.drawing_upload_path, validators=[apps.engineering.models.validate_drawing_file])),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_drawings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drawings', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='crm.order')),
                ('parent_drawing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='engineering.drawing')),
            ],
            options={
                'verbose_name': 'Drawing',
                'verbose_name_plural': 'Drawings',
                'ordering': ['-created_at'],
                'unique_together': {('order', 'drawing_number', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DrawingComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='engineering.drawing')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drawing Comment',
                'verbose_name_plural': 'Drawing Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
