# Generated by Django 4.2.9 on 2026-01-30 07:01

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_planned', models.PositiveIntegerField(default=0)),
                ('total_produced', models.PositiveIntegerField(default=0)),
                ('total_ok', models.PositiveIntegerField(default=0)),
                ('total_rework', models.PositiveIntegerField(default=0)),
                ('total_rejection', models.PositiveIntegerField(default=0)),
                ('overall_ok_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('overall_rework_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('overall_rejection_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('overall_yield_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_summary', to='crm.order')),
            ],
            options={
                'verbose_name': 'Production Summary',
                'verbose_name_plural': 'Production Summaries',
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('production_date', models.DateField()),
                ('shift', models.CharField(choices=[('day', 'Day Shift'), ('night', 'Night Shift'), ('general', 'General Shift')], default='general', max_length=20)),
                ('planned_quantity', models.PositiveIntegerField(default=0)),
                ('produced_quantity', models.PositiveIntegerField(default=0)),
                ('ok_quantity', models.PositiveIntegerField(default=0)),
                ('rework_quantity', models.PositiveIntegerField(default=0)),
                ('rejection_quantity', models.PositiveIntegerField(default=0)),
                ('ok_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('rework_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('rejection_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('total_yield_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('rejection_reasons', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='crm.order')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_records', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_production_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Production Record',
                'verbose_name_plural': 'Production Records',
                'ordering': ['-production_date', '-created_at'],
                'unique_together': {('order', 'production_date', 'shift')},
            },
        ),
    ]
