# Generated by Django 4.2.9 on 2026-01-30 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingStandard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Packing Standard',
                'verbose_name_plural': 'Packing Standards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('packing_details', models.TextField(blank=True, null=True)),
                ('total_packages', models.PositiveIntegerField(default=0)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Gross weight in KG', max_digits=10, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Net weight in KG', max_digits=10, null=True)),
                ('dimensions', models.CharField(blank=True, help_text='L x W x H in cm', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('packing', 'Packing in Progress'), ('packed', 'Packed'), ('ready', 'Ready for Dispatch'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('transport_mode', models.CharField(choices=[('road', 'Road Transport'), ('rail', 'Rail Transport'), ('air', 'Air Freight'), ('sea', 'Sea Freight'), ('courier', 'Courier'), ('self_pickup', 'Self Pickup')], default='road', max_length=20)),
                ('transport_scope', models.CharField(choices=[('ex_works', 'Ex-Works'), ('fob', 'FOB'), ('cif', 'CIF'), ('door_delivery', 'Door Delivery')], default='ex_works', max_length=20)),
                ('transporter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('e_way_bill_number', models.CharField(blank=True, max_length=50, null=True)),
                ('lr_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='LR Number')),
                ('planned_dispatch_date', models.DateField(blank=True, null=True)),
                ('actual_dispatch_date', models.DateField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('delivery_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dispatches', to=settings.AUTH_USER_MODEL)),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_orders', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='crm.order')),
                ('packed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packed_dispatches', to=settings.AUTH_USER_MODEL)),
                ('packing_standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='logistics.packingstandard')),
            ],
            options={
                'verbose_name': 'Order Dispatch',
                'verbose_name_plural': 'Order Dispatches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('packing_list', 'Packing List'), ('delivery_challan', 'Delivery Challan'), ('e_way_bill', 'E-Way Bill'), ('test_certificate', 'Test Certificate'), ('warranty_card', 'Warranty Card'), ('other', 'Other')], max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='dispatch_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='logistics.orderdispatch')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispatch Document',
                'verbose_name_plural': 'Dispatch Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
