# Generated by Django 4.2.9 on 2026-01-30 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricationProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('cutting', 'Cutting'), ('forming', 'Forming'), ('joining', 'Joining'), ('finishing', 'Finishing'), ('assembly', 'Assembly')], default='cutting', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('sequence_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fabrication Process',
                'verbose_name_plural': 'Fabrication Processes',
                'ordering': ['sequence_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderFabrication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('skipped', 'Skipped')], default='not_started', max_length=20)),
                ('planned_quantity', models.PositiveIntegerField(default=0)),
                ('completed_quantity', models.PositiveIntegerField(default=0)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('machine', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fabrications', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_fabrications', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabrication_processes', to='crm.order')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_fabrications', to='fabrication.fabricationprocess')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fabrications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Fabrication',
                'verbose_name_plural': 'Order Fabrications',
                'ordering': ['process__sequence_order'],
                'unique_together': {('order', 'process')},
            },
        ),
        migrations.CreateModel(
            name='FabricationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('skipped', 'Skipped')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('skipped', 'Skipped')], max_length=20)),
                ('quantity_completed', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_fabrication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='fabrication.orderfabrication')),
            ],
            options={
                'verbose_name': 'Fabrication Log',
                'verbose_name_plural': 'Fabrication Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
