# Generated by Django 4.2.9 on 2026-01-30 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Treatment Type',
                'verbose_name_plural': 'Treatment Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderSurfaceTreatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('planned_quantity', models.PositiveIntegerField(default=0)),
                ('completed_quantity', models.PositiveIntegerField(default=0)),
                ('rejected_quantity', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('thickness_microns', models.DecimalField(blank=True, decimal_places=2, help_text='Coating thickness in microns', max_digits=8, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_outsourced', models.BooleanField(default=False)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surface_treatments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surface_treatments', to='crm.order')),
                ('treatment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_treatments', to='surface_treatment.treatmenttype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_surface_treatments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Surface Treatment',
                'verbose_name_plural': 'Order Surface Treatments',
                'ordering': ['-created_at'],
                'unique_together': {('order', 'treatment_type')},
            },
        ),
    ]
