# Generated by Django 4.2.9 on 2026-01-30 07:01

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('thickness', models.DecimalField(blank=True, decimal_places=3, help_text='Thickness in mm', max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=3, help_text='Width in mm', max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=3, help_text='Length in mm', max_digits=10, null=True)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('gram', 'Gram'), ('meter', 'Meter'), ('mm', 'Millimeter'), ('piece', 'Piece'), ('sheet', 'Sheet'), ('liter', 'Liter')], default='kg', max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('stock_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Minimum stock level for alerts', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Material Type',
                'verbose_name_plural': 'Material Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('issued_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('consumed_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('returned_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('requested', 'Requested'), ('partially_issued', 'Partially Issued'), ('fully_issued', 'Fully Issued'), ('returned', 'Returned')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_order_materials', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_order_materials', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_materials', to='materials.material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='crm.order')),
            ],
            options={
                'verbose_name': 'Order Material',
                'verbose_name_plural': 'Order Materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('scrap', 'Scrap')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('stock_before', models.DecimalField(decimal_places=3, max_digits=12)),
                ('stock_after', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='materials.material')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transactions', to='crm.order')),
            ],
            options={
                'verbose_name': 'Material Transaction',
                'verbose_name_plural': 'Material Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='materials.materialtype'),
        ),
    ]
