# Generated by Django 4.2.9 on 2026-01-30 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('stage', models.CharField(choices=[('incoming', 'Incoming Inspection'), ('in_process', 'In-Process Inspection'), ('final', 'Final Inspection'), ('pdi', 'Pre-Dispatch Inspection')], default='in_process', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inspection Type',
                'verbose_name_plural': 'Inspection Types',
                'ordering': ['stage', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspected_quantity', models.PositiveIntegerField(default=0)),
                ('passed_quantity', models.PositiveIntegerField(default=0)),
                ('failed_quantity', models.PositiveIntegerField(default=0)),
                ('rework_quantity', models.PositiveIntegerField(default=0)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail'), ('conditional', 'Conditional Pass'), ('rework', 'Rework Required')], default='pending', max_length=20)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('is_qa_approved', models.BooleanField(default=False)),
                ('qa_approved_at', models.DateTimeField(blank=True, null=True)),
                ('qa_remarks', models.TextField(blank=True, null=True)),
                ('defects_found', models.TextField(blank=True, null=True)),
                ('corrective_action', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_inspections', to=settings.AUTH_USER_MODEL)),
                ('inspection_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_inspections', to='inspection.inspectiontype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='crm.order')),
                ('qa_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_approved_inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Inspection',
                'verbose_name_plural': 'Order Inspections',
                'ordering': ['-inspection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parameter', models.CharField(max_length=255)),
                ('specification', models.CharField(blank=True, max_length=255, null=True)),
                ('actual_value', models.CharField(blank=True, max_length=255, null=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='inspection.orderinspection')),
            ],
            options={
                'verbose_name': 'Inspection Checklist Item',
                'verbose_name_plural': 'Inspection Checklist Items',
                'ordering': ['created_at'],
            },
        ),
    ]
